import ThemeButton from "./components/ThemeButton";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[rgb(241,241,241)] dark:text-[#ffffff]  dark:bg-[#232222]">
        <header className="dark:bg-[#232222] dark:text-[#ffffff] shadow-[0_0px_24px_rgba(0,0,0,0.22)] h-fit w-full p-[10]">
          <nav className=" max-w-[1100] m-auto">
            <ul className="flex justify-between p-[5] capitalize">
              <li className="font-bold text-[20px]">where is the world?</li>
              <li className="font-semibold capitalize">
                <ThemeButton />
                </li>
            </ul>
          </nav>
        </header>
        <NuqsAdapter>
          {children}
        </NuqsAdapter>
        
      </body>
    </html>
  );
}
