import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#f1f1f1]">
        <header className="shadow-[0_0px_24px_rgba(0,0,0,0.22)] h-fit w-full p-[10]">
          <nav className=" max-w-[1100] m-auto">
            <ul className="flex justify-between p-[5] capitalize">
              <li className="font-bold text-[20px]">where is the world?</li>
              <li className="font-semibold capitalize">
                <button className="Theme font-semibold capitalize py-[5] px-[7] rounded-[7]  hover:bg-[#ececec]">
                <span className="dark font-semibold capitalize">dark</span>
                <span className="light font-semibold capitalize">light</span>
                </button>
                </li>
            </ul>
          </nav>
        </header>
        {children}
        
      </body>
    </html>
  );
}
